### ISSUE TITLE
Windows Defender Reports Severe Threat

### ISSUE THREAD

**Issue by Razorwalker** [STOCD/OSCR-UI#38]
So, I unzipped the file and Windows Defender immediately quarantined the .exe and classified it as a Trojan:Win32/Wacatac.B!ml. I have attached a screenshot of Windows Defender's report. 

<img width="897" alt="virus" src="https://github.com/STOCD/OSCR-UI/assets/33007523/12396e11-b9fb-4471-98d1-52da0b53bf5f">

**Comment by Kraust** [comment]
This will hopefully be resolved in #39

**Comment by Kraust** [comment]
Marking as resolved with the resolution of #39. 

If the issue persists please let us know.

Smart Screen will detect the MSI as unsigned. This is normal behavior as we do not sign our MSI (or our executable).
